# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 455f38bf4e1f1163e6ede9ae79f1543d88fae75d099ee3626aaf04009b2a10edb03ceb46d55b935afd74007295036af96c154f96a472b94434c5932016284011

test:
  secret_key_base: eedce25f91ddbab19459222d2f4934c54238a109978b5b404b0f5181dd0ad49d45b911e1dc62166cf15c403320c8d2c1c8cd097a8d5a6bc40ca1512b18653557

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
